-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 00:35:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `User_policy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User_policy` ;

CREATE TABLE IF NOT EXISTS `User_policy` (
  `idUser_policy` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `tier` INT NOT NULL,
  UNIQUE INDEX `idUser_prava_UNIQUE` (`idUser_policy` ASC) VISIBLE,
  PRIMARY KEY (`idUser_policy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `postCode` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `id_policy` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_user_policy_id_policy`
    FOREIGN KEY ()
    REFERENCES `User_policy` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `User_policy`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `User_policy` (`idUser_policy`, `name`, `tier`) VALUES (1, 'SuperAdmin', 20);
INSERT INTO `User_policy` (`idUser_policy`, `name`, `tier`) VALUES (2, 'Admin', 10);
INSERT INTO `User_policy` (`idUser_policy`, `name`, `tier`) VALUES (3, 'Warehouse', 5);
INSERT INTO `User_policy` (`idUser_policy`, `name`, `tier`) VALUES (4, 'Customer', 2);

COMMIT;

